version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        env: dev
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      args:
        FRONTEND_ENV: dev
    stdin_open: true